# fly.toml app configuration file generated for convertor-pacote-agranel on 2025-09-01T15:43:16-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'convertor-pacote-agranel'
primary_region = 'gru'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[[mounts]]
  source = 'app_data'
  destination = '/etc/secrets'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1   
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
